create database SQLAssignment1
use SQLAssignment1
CREATE TABLE Workers (
    WORKER_ID INT PRIMARY KEY,
	FIRST_NAME CHAR(25) NOT NULL,
	LAST_NAME CHAR(25),
	SALARY int CHECK (salary Between 10000 and 25000),
	JOINING_DATE DATETIME,
	DEPARTMENT CHAR(25) CHECK(Department in('IT','Sales','HR','Accounts')),
);
select * from Workers
INSERT INTO workers (WORKER_ID, FIRST_NAME,LAST_NAME, SALARY, JOINING_DATE , DEPARTMENT)
VALUES
(1, 'Priya', 'Jaiswal', 13000 ,'2016-06-15 00:00:00', 'IT'),
(2, 'Erica', 'Attal', 11200, '2022-09-25 00:00:00', 'Sales'),
(3, 'Srishti', 'Kaushik', 16700, '2006-07-30 00:00:00', 'HR')

SELECT FIRST_NAME AS WORKER_NAME FROM Workers;
SELECT upper(FIRST_NAME) AS FIRST_NAME FROM Workers;
INSERT INTO workers (WORKER_ID, FIRST_NAME,LAST_NAME, SALARY, JOINING_DATE , DEPARTMENT)
VALUES
(4, 'Priyanka', 'Jaiswal', 13000 ,'2016-06-15 00:00:00', 'IT'),
(5, 'Eric', 'Attal', 11200, '2022-09-25 00:00:00', 'Accounts'),
(6, 'Srish', 'Kaushik', 16700, '2006-07-30 00:00:00', 'HR')

SELECT DISTINCT DEPARTMENT FROM Workers;
SELECT LEFT(FIRST_NAME, 3) AS FIRST_NAME FROM Workers;
SELECT CHARINDEX('a' , FIRST_NAME) AS 'Position of a' 
FROM Workers 
WHERE FIRST_NAME = 'Priya';
SELECT rtrim(FIRST_NAME)AS FIRST_NAME FROM Workers;
SELECT ltrim(DEPARTMENT)AS DEPARTMENT FROM Workers;
SELECT DISTINCT LEN(DEPARTMENT) as length,DEPARTMENT FROM Workers;
SELECT REPLACE(FIRST_NAME, 'a', 'A') AS FIRST_NAME
FROM Workers;
SELECT CONCAT(FIRST_NAME,'', LAST_NAME) AS Full_NAME
FROM Workers;
SELECT *
FROM Workers
ORDER BY FIRST_NAME ASC;
SELECT *
FROM Workers
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;
SELECT *
FROM Workers
WHERE FIRST_NAME IN ('Priya', 'Erica');
SELECT *
FROM Workers
WHERE FIRST_NAME NOT IN ('Priya', 'Erica');
SELECT *
FROM Workers
WHERE DEPARTMENT = 'HR';
SELECT *
FROM Workers
WHERE FIRST_NAME LIKE '%a%';

SELECT *
FROM Workers
WHERE FIRST_NAME LIKE '%a';
SELECT *
FROM Workers
WHERE FIRST_NAME LIKE '______h';
SELECT *
FROM Workers
WHERE SALARY BETWEEN 10000 AND 50000;
SELECT *
FROM Workers
WHERE MONTH(JOINING_DATE) = 2 AND YEAR(JOINING_DATE) = 2014;
SELECT COUNT(*) AS COUNT
FROM Workers
WHERE DEPARTMENT = 'HR';